version: "2"
services:
  forecasting:
    image: corticaldata/forecasting
    container_name: forecasting
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      JAVA_OPTS: "-Xms384m -Xmx384m"
    restart: always
